#!/bin/bash

######################################################################

function edit_hosts() { sudo vi /etc/hosts; }

###################################

function install_prerequisites()
{
	echo "Checking prerequisites ..."

	if [ ! -x "$(which brew)" ]; then
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi

	brew install bash-completion
	brew install thefuck
	brew install p7zip
	brew install graphviz # for deps tree
	brew install gnu-sed # gsed
	brew install subversion
	brew install git
	brew install python3
	brew install mingw-w64
	brew install cask

	brew cask install docker
	brew      install docker-compose
	brew cask install virtualbox
	brew cask install vagrant	

	# completion for docker
	ln -s /Applications/Docker.app/Contents/Resources/etc/docker.bash-completion /usr/local/etc/bash_completion.d/docker

	echo "Done"
}

###################################

function brew_deps_tree()
{
	brew graph --installed | dot -T png -o graph.png
	open graph.png
}

###################################

#https://gist.github.com/mathiasbynens/674099
function appify()
{
	APPNAME=${2:-$(basename "$1" ".sh")}
	DIR="$APPNAME.app/Contents/MacOS"

	if [ -a "$APPNAME.app" ]; then
		echo "$PWD/$APPNAME.app already exists :("
		exit 1
	fi

	mkdir -p "$DIR"
	cp "$1" "$DIR/$APPNAME"
	chmod +x "$DIR/$APPNAME"

	echo "$PWD/$APPNAME.app"
}

###################################

function python_module_check()
{
	local PYTHON="python3"
	local PIP="pip3"

	module=$1
	if [ -z ${module} ]; then
		echo "Module not set"
		return 1
	fi

	echo "Checking python module \"${module}\" ..."

	${PYTHON} -c "import ${module}"
	res=$?

	if [ ${res} == 0 ]; then
		echo "Module found"
	else
		read -p "Module not found! Install? Y/[n] " yn
		if [ "${yn}" == "Y" ]; then
			${PIP} install ${module}
		fi
	fi
}

###################################

function set_prompt()
{
	local COLOR_NC='\e[0m' # No Color
	local COLOR_WHITE='\e[1;37m'
	local COLOR_BLACK='\e[0;30m'
	local COLOR_BLUE='\e[0;34m'
	local COLOR_LIGHT_BLUE='\e[1;34m'
	local COLOR_GREEN='\e[0;32m'
	local COLOR_LIGHT_GREEN='\e[1;32m'
	local COLOR_CYAN='\e[0;36m'
	local COLOR_LIGHT_CYAN='\e[1;36m'
	local COLOR_RED='\e[0;31m'
	local COLOR_LIGHT_RED='\e[1;31m'
	local COLOR_PURPLE='\e[0;35m'
	local COLOR_LIGHT_PURPLE='\e[1;35m'
	local COLOR_BROWN='\e[0;33m'
	local COLOR_YELLOW='\e[1;33m'
	local COLOR_GRAY='\e[0;30m'
	local COLOR_LIGHT_GRAY='\e[0;37m'

	# wrap colors in \[\]
	for var in $(set | grep --color=never "local COLOR_" | grep -v grep | awk '{$1=$1;print}' | cut -d ' ' -f 2); do
		name=$(echo $var | cut -d '=' -f 1)
		value=$(echo $var | cut -d '=' -f 2 | cut -d "'" -f 2)
		value="\\[$value\\]"
		declare ${name}="${value}"
	done

	local KEY_TIME='\t'
	local KEY_USER='\u'
	local KEY_HOST='\h'
	local KEY_DIR='\w'
	local KEY_DIR_SHORT='\W'

#	case $TERM in
#	xterm*)
#		TITLEBAR="\e]0;$KEY_USER@$KEY_HOST:$KEY_DIR\a"
#		;;
#	*)
#		TITLEBAR=""
#		;;
#	esac

	PS1="$TITLEBAR\
$COLOR_WHITE[$KEY_TIME]$COLOR_NC \
$COLOR_WHITE($COLOR_NC\
$COLOR_CYAN\$?$COLOR_NC\
$COLOR_WHITE)$COLOR_NC \
$COLOR_YELLOW$KEY_USER$COLOR_NC\
$COLOR_RED@$COLOR_NC\
$COLOR_LIGHT_GREEN$KEY_HOST$COLOR_NC \
$COLOR_GREEN$KEY_DIR_SHORT$COLOR_NC\
\$ "

	PS2='> '
	PS4='+ '
}

###################################

function on_remote()
{
	# don't do anything, need to research more regarging ssh agents etc.
	return 1

#	SSH_AUTH_SOCK=$(ls /tmp/*launchd*/Listeners)
#	EXEC_SA="ssh-agent -sssss"

#	echo "Currenty active ssh-agents:"
#	ps auxww | grep ${EXEC_SA} | grep -v grep | sort

#	echo "Killing older ones ..."
#	ps -x -o pid,command | grep --color=never ${EXEC_SA} | grep -v grep | cut -d' ' -f 1 | xargs kill -KILL

#	eval `${EXEC_SA}`
#	ssh-add -K

#	echo "Done, new one started, agents running:"
#	ps auxww | grep ${EXEC_SA} | grep -v grep | sort
}

######################################################################

if [ -x "$(which thefuck)" ]; then
	eval $(thefuck --alias)
fi

if [ -f $(brew --prefix)/etc/bash_completion ]; then
	. $(brew --prefix)/etc/bash_completion
fi

#	#remote connection
#	if [ ! -z "${SSH_CLIENT}" ]; then
#		echo "Welcome, stranger"
#		on_remote
#	fi

#alias ls="ls -hF"

#if [[ "$OSTYPE" == "linux-gnu" ]]; then
#	alias ls="ls --color"
#elif [[ "$OSTYPE" == "darwin"* ]]; then
#	alias ls="ls -G"

alias start="open -n -a"
alias vlc="/Applications/VLC.app/Contents/MacOS/VLC"
alias cvlc="vlc --intf ncurses --no-color" # VLC in console mode
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

alias ll="ls -l"
alias l="ll -a"
alias lld="ll -d */"

alias lessn="less -N"
alias lessf="less +F"

alias grep="grep --color=always"

export SVN_EDITOR=$(which vi)
alias svnst="svn status"
alias svnadd="svn status | grep --color=never \"?\" | cut -d \"?\" -f 2 | sed \"s/^ *//;s/ *$//\" | sed \"s/^/\\\"/;s/$/\\\"/\" | xargs -L1 svn add"
alias svndel="svn status | grep --color=never \"!\" | cut -d \"!\" -f 2 | sed \"s/^ *//;s/ *$//\" | sed \"s/^/\\\"/;s/$/\\\"/\" | xargs -L1 svn del"

set_prompt

