#!/bin/bash

###################################

function set_prompt()
{
	local COLOR_NC='\e[0m' # No Color
	local COLOR_WHITE='\e[1;37m'
	local COLOR_BLACK='\e[0;30m'
	local COLOR_BLUE='\e[0;34m'
	local COLOR_LIGHT_BLUE='\e[1;34m'
	local COLOR_GREEN='\e[0;32m'
	local COLOR_LIGHT_GREEN='\e[1;32m'
	local COLOR_CYAN='\e[0;36m'
	local COLOR_LIGHT_CYAN='\e[1;36m'
	local COLOR_RED='\e[0;31m'
	local COLOR_LIGHT_RED='\e[1;31m'
	local COLOR_PURPLE='\e[0;35m'
	local COLOR_LIGHT_PURPLE='\e[1;35m'
	local COLOR_BROWN='\e[0;33m'
	local COLOR_YELLOW='\e[1;33m'
	local COLOR_GRAY='\e[0;30m'
	local COLOR_LIGHT_GRAY='\e[0;37m'

	# wrap colors in \[\]
	for var in $(set | grep --color=never "local COLOR_" | grep -v grep | awk '{$1=$1;print}' | cut -d ' ' -f 2); do
		name=$(echo $var | cut -d '=' -f 1)
		value=$(echo $var | cut -d '=' -f 2 | cut -d "'" -f 2)
		value="\\[$value\\]"
		declare ${name}="${value}"
	done

	local KEY_TIME='\t'
	local KEY_USER='\u'
	local KEY_HOST='\h'
	local KEY_DIR='\w'
	local KEY_DIR_SHORT='\W'

#	case $TERM in
#	xterm*)
#		TITLEBAR="\e]0;$KEY_USER@$KEY_HOST:$KEY_DIR\a"
#		;;
#	*)
#		TITLEBAR=""
#		;;
#	esac

	PS1="$TITLEBAR\
$COLOR_WHITE[$KEY_TIME]$COLOR_NC \
$COLOR_WHITE($COLOR_NC\
$COLOR_CYAN\$?$COLOR_NC\
$COLOR_WHITE)$COLOR_NC \
$COLOR_YELLOW$KEY_USER$COLOR_NC\
$COLOR_RED@$COLOR_NC\
$COLOR_LIGHT_GREEN$KEY_HOST$COLOR_NC \
$COLOR_GREEN$KEY_DIR_SHORT$COLOR_NC\
\$ "

	PS2='> '
	PS4='+ '
}

###################################

alias ls="ls -hF"
alias ls="ls --color"

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

alias ll="ls -l"
alias l="ll -a"
alias lld="ll -d */"

alias lessn="less -N"
alias lessf="less +F"

alias grep="grep --color=always"

set_prompt

